/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ViewRouteImport } from "./routes/view"
import { Route as RandomRouteImport } from "./routes/random"
import { Route as EditRouteImport } from "./routes/edit"
import { Route as IndexRouteImport } from "./routes/index"

const ViewRoute = ViewRouteImport.update({
  id: "/view",
  path: "/view",
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: "/random",
  path: "/random",
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/edit": typeof EditRoute
  "/random": typeof RandomRoute
  "/view": typeof ViewRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/edit": typeof EditRoute
  "/random": typeof RandomRoute
  "/view": typeof ViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/edit": typeof EditRoute
  "/random": typeof RandomRoute
  "/view": typeof ViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/edit" | "/random" | "/view"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/edit" | "/random" | "/view"
  id: "__root__" | "/" | "/edit" | "/random" | "/view"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditRoute: typeof EditRoute
  RandomRoute: typeof RandomRoute
  ViewRoute: typeof ViewRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/view": {
      id: "/view"
      path: "/view"
      fullPath: "/view"
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/random": {
      id: "/random"
      path: "/random"
      fullPath: "/random"
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/edit": {
      id: "/edit"
      path: "/edit"
      fullPath: "/edit"
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditRoute: EditRoute,
  RandomRoute: RandomRoute,
  ViewRoute: ViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
